--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/DaPigGuy/PiggyCrates
branches:
- master
- 2.0.0
projects:
  PiggyCrates:
    path: ""
    lib:
      - src: CortexPE/Commando/Commando
        version: ^0.5
...
