# PiggyCrates Configuration

# ID:DMG value of keys
key: "131:0"

# Description of keys
key-lore: "Use this key to get rewards."

# Allow the creation & destruction of crates by those without the piggycrates.crates permission node
allow-crate-changes: false
